# 线上配置文件
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shampohoe_api
    username: root
    password: lai751026
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
#    password: 123456
    rabbitmq:
      host: 192.168.159.131
      port: 5672
      username: root
      password: lai751026
      virtual-host: /
      listener:
        simple:
          prefetch: 5
          acknowledge-mode: auto
          retry:
            enabled: true
            initial-interval: 1000ms
            multiplier: 1
            max-attempts: 3
#  redisson:
 #   config: classpath:classpath:redisson.yml
  #实现分布式锁
 # redission:
   # config: classpath:redisson.yml
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''